In [1]:
import pandas as pd 
import json

## All groups info

In [3]:
with open("../output/groups_info.json", "r") as f:
    groups_info = json.load(f)

In [7]:
df = pd.DataFrame(groups_info).T

df['unique_tags_pr_work'] = df['n_unique_tags'] / df['n_works']

In [8]:
df

,n_works,angst_count,fluff_count,hurt_comfort_count,n_bang_tags,n_slash_tags,n_unique_tags,unique_tags_pr_work
Harry Potter,256461,24276,25837,13560,14840,500692,567010,2.210901
Dream SMP,66675,16526,10917,13216,7622,89880,241889,3.627882
The X-Files RPF,377,23,37,3,1,418,542,1.437666
Medium Fandoms,18466,1634,2302,868,1576,31372,71472,3.870465
Small Fandoms,2885,207,188,93,148,4565,23470,8.135182

## Harry Potter

In [10]:
with open("../output/Harry Potter/slash_tags_counter.json", "r") as f:
    hp_slash = json.load(f)

In [20]:
hp_slash_df = pd.DataFrame.from_dict(hp_slash,orient="index" ).reset_index()
hp_slash_df = hp_slash_df.rename(columns={'index':'tag', 0:'count'})

hp_slash_df.sort_values("count", ascending=False).head(50)

                                                    tag  count
11                             Sirius Black/Remus Lupin  16505
10                                         Hurt/Comfort  13560
16                            Draco Malfoy/Harry Potter  11873
3                Draco Malfoy/Harry Potter Draco Malfoy  11347
81                       James Potter/Lily Evans Potter   9103
86       Hermione Granger/Draco Malfoy Hermione Granger   8808
63               Draco Malfoy/Harry Potter Harry Potter   8438
48                Sirius Black/Remus Lupin Sirius Black   7888
144                        Hermione Granger/Ron Weasley   7055
93                        Hermione Granger/Draco Malfoy   6736
4                            Harry Potter/Ginny Weasley   6402
1465                         Regulus Black/James Potter   6027
232                      Implied/Referenced Child Abuse   5135
130                              Emotional Hurt/Comfort   5002
149                    Plot What Plot/Porn Without Plot   4344
2043                   Marlene McKinnon/Dorcas Meadowes   3704
51              Harry Potter/Severus Snape Harry Potter   3362
77                 Sirius Black/Remus Lupin Remus Lupin   3313
384                                      Grief/Mourning   3114
502                              Angst and Hurt/Comfort   2781
153          Hermione Granger/Draco Malfoy Draco Malfoy   2756
13      Hermione Granger/Severus Snape Hermione Granger   2722
87          James Potter/Lily Evans Potter James Potter   2712
0                               Harry Potter/Tom Riddle   2444
79              Harry Potter/Ginny Weasley Harry Potter   2325
5             Hermione Granger/Ron Weasley Harry Potter   2277
404                 Lucius Malfoy/Narcissa Black Malfoy   2221
49                        Hermione Granger/Harry Potter   2111
185                          Harry Potter/Severus Snape   2091
37                                              Dom/sub   2018
15                 Harry Potter/Tom Riddle Harry Potter   1872
363          Hermione Granger/Harry Potter Harry Potter   1776
12          James Potter/Lily Evans Potter Sirius Black   1663
168                                    Action/Adventure   1638
188                               Rape/Non-con Elements   1606
350                                     Friendship/Love   1585
129       Hermione Granger/Ron Weasley Hermione Granger   1580
425                 Harry Potter/Tom Riddle | Voldemort   1572
57                                        Light Dom/sub   1551
156                  Implied/Referenced Character Death   1499
289    Harry Potter/Tom Riddle | Voldemort Harry Potter   1414
34581                      Barty Crouch Jr./Evan Rosier   1404
377     Alternate Universe - Everyone Lives/Nobody Dies   1398
1172                       Implied/Referenced Self-Harm   1389
505             Alternate Universe - College/University   1370
2953               Established Sirius Black/Remus Lupin   1367
730                               Ambiguous/Open Ending   1348
1970                   Mary Macdonald/Lily Evans Potter   1340
236                      Hermione Granger/Severus Snape   1304
229                         Luna Lovegood/Ginny Weasley   1260

## Dream SMP

In [21]:
with open("../output/Dream SMP/slash_tags_counter.json", "r") as f:
    dsmp_slash = json.load(f)

In [22]:
dsmp_slash_df = pd.DataFrame.from_dict(dsmp_slash,orient="index" ).reset_index()
dsmp_slash_df = dsmp_slash_df.rename(columns={'index':'tag', 0:'count'})

dsmp_slash_df.sort_values("count", ascending=False).head(50)

                                                   tag  count
5                                         Hurt/Comfort  13216
59    Clay | Dream/GeorgeNotFound (Video Blogging RPF)   4576
16                              Emotional Hurt/Comfort   3493
20        Alternate Universe - Superheroes/Superpowers   2712
41                      Implied/Referenced Child Abuse   2687
65                              Angst and Hurt/Comfort   2559
56                  Implied/Referenced Character Death   2083
21                       Alexis | Quackity/Wilbur Soot   2029
55                Alexis | Quackity/Karl Jacobs/Sapnap   2028
24                          Implied/Referenced Suicide   1775
66                  Kristin Rosales Watson/Phil Watson   1673
9                                   Karl Jacobs/Sapnap   1471
245                              Ambiguous/Open Ending   1372
98                                      Grief/Mourning   1317
4                         Implied/Referenced Self-Harm   1243
57                          Implied/Referenced Torture   1193
6                                         Rape/Non-Con    970
1                                    Mild Hurt/Comfort    969
46   He/Him and They/Them Pronouns for Ranboo (Vide...    855
7                           Alexis | Quackity/Jschlatt    777
19       Clay | Dream/Technoblade (Video Blogging RPF)    754
67                            Implied/Referenced Abuse    724
139           Clay | Dream/Sapnap (Video Blogging RPF)    682
22                           Ranboo/Toby Smith | Tubbo    645
177                      Emotional/Psychological Abuse    637
131                           Alcohol Abuse/Alcoholism    571
47                  Cara | CaptainPuffy/Niki | Nihachu    537
140                            Age Regression/De-Aging    532
133                             Fluff and Hurt/Comfort    515
43         Implied/Referenced Alcohol Abuse/Alcoholism    513
79             Alternate Universe - College/University    503
96          GeorgeNotFound/Sapnap (Video Blogging RPF)    485
11                        Zak Ahmed/Darryl Noveschosch    470
10                 Ponk | DropsByPonk/Sam | Awesamdude    470
39   Clay | Dream/GeorgeNotFound/Sapnap (Video Blog...    427
262                           Alexis | Quackity/Sapnap    409
101                   Plot What Plot/Porn Without Plot    383
235   They/Them Pronouns for Eret (Video Blogging RPF)    376
168                      Alexis | Quackity/Karl Jacobs    368
154  They/Them Pronouns for Ranboo (Video Blogging ...    366
220                        Clay | Dream/Floris | Fundy    336
27   Zak Ahmed | Skeppy/Darryl Noveschosch | BadBoy...    322
215                               Jschlatt/Wilbur Soot    316
129                        Implied/Referenced Drug Use    314
146                           Clay | Dream/Luke | Punz    305
109                                 Wilbur Soot/Reader    291
371                           Clay | Dream/Wilbur Soot    282
2                                              Dom/sub    276
87                     Implied/Referenced Rape/Non-con    272
175                              Rape/Non-con Elements    267

## X Files

In [ ]:
with open("../output/The X-Files RPF/slash_tags_counter.json", "r") as f:
    hp_slash = json.load(f)

In [ ]:
hp_slash_df = pd.DataFrame.from_dict(hp_slash,orient="index" ).reset_index()
hp_slash_df = hp_slash_df.rename(columns={'index':'tag', 0:'count'})

hp_slash_df.sort_values("count", ascending=False).head(50)

                                                    tag  count
11                             Sirius Black/Remus Lupin  16505
10                                         Hurt/Comfort  13560
16                            Draco Malfoy/Harry Potter  11873
3                Draco Malfoy/Harry Potter Draco Malfoy  11347
81                       James Potter/Lily Evans Potter   9103
86       Hermione Granger/Draco Malfoy Hermione Granger   8808
63               Draco Malfoy/Harry Potter Harry Potter   8438
48                Sirius Black/Remus Lupin Sirius Black   7888
144                        Hermione Granger/Ron Weasley   7055
93                        Hermione Granger/Draco Malfoy   6736
4                            Harry Potter/Ginny Weasley   6402
1465                         Regulus Black/James Potter   6027
232                      Implied/Referenced Child Abuse   5135
130                              Emotional Hurt/Comfort   5002
149                    Plot What Plot/Porn Without Plot   4344
2043                   Marlene McKinnon/Dorcas Meadowes   3704
51              Harry Potter/Severus Snape Harry Potter   3362
77                 Sirius Black/Remus Lupin Remus Lupin   3313
384                                      Grief/Mourning   3114
502                              Angst and Hurt/Comfort   2781
153          Hermione Granger/Draco Malfoy Draco Malfoy   2756
13      Hermione Granger/Severus Snape Hermione Granger   2722
87          James Potter/Lily Evans Potter James Potter   2712
0                               Harry Potter/Tom Riddle   2444
79              Harry Potter/Ginny Weasley Harry Potter   2325
5             Hermione Granger/Ron Weasley Harry Potter   2277
404                 Lucius Malfoy/Narcissa Black Malfoy   2221
49                        Hermione Granger/Harry Potter   2111
185                          Harry Potter/Severus Snape   2091
37                                              Dom/sub   2018
15                 Harry Potter/Tom Riddle Harry Potter   1872
363          Hermione Granger/Harry Potter Harry Potter   1776
12          James Potter/Lily Evans Potter Sirius Black   1663
168                                    Action/Adventure   1638
188                               Rape/Non-con Elements   1606
350                                     Friendship/Love   1585
129       Hermione Granger/Ron Weasley Hermione Granger   1580
425                 Harry Potter/Tom Riddle | Voldemort   1572
57                                        Light Dom/sub   1551
156                  Implied/Referenced Character Death   1499
289    Harry Potter/Tom Riddle | Voldemort Harry Potter   1414
34581                      Barty Crouch Jr./Evan Rosier   1404
377     Alternate Universe - Everyone Lives/Nobody Dies   1398
1172                       Implied/Referenced Self-Harm   1389
505             Alternate Universe - College/University   1370
2953               Established Sirius Black/Remus Lupin   1367
730                               Ambiguous/Open Ending   1348
1970                   Mary Macdonald/Lily Evans Potter   1340
236                      Hermione Granger/Severus Snape   1304
229                         Luna Lovegood/Ginny Weasley   1260